pretty-simple.cabal, stack.yaml
This avoids cabal running into the compile failure below:
```
Configuring component lib from pretty-simple-1.0.0.3...
Preprocessing library pretty-simple-1.0.0.3...
[1 of 7] Compiling Text.Pretty.Simple.Internal.Output ( src/Text/Pretty/Simple/Internal/Output.hs, /tmp/matrix-worker/1484457210/dist-newstyle/build/x86_64-linux/ghc-7.8.4/pretty-simple-1.0.0.3/build/Text/Pretty/Simple/Internal/Output.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package bytestring-0.10.4.0 ... linking ... done.
Loading package transformers-0.3.0.0 ... linking ... done.
Loading package mtl-2.1.3.1 ... …
```
=> Correct version bounds to avoid compile failure

src/Debug/Pretty/Simple.hs
Related issue: https://github.com/cdepillabout/pretty-simple/issues/15
**Notes**:
- I carried all comments from [Debug.Trace](https://hackage.haskell.org/package/base-4.10.0.0/docs/Debug-Trace.html) module to here. I think it also would present good documentation for readers of this module.
=> Add Debug.Pretty.Simple module for pretty debugging

src/Debug/Pretty/Simple.hs
Fixes #19
This PR adds `NoColor` counterparts of trace functions, and implement tests on them (because testing colored output is awkward).
@cdepillabout There is a warning introduced with this PR:
```
warning: [-Wunused-imports]
The qualified import of ‘Data.Map’ is redundant
except perhaps to import instances from ‘Data.Map’
To import instances alone, use: import Data.Map()
```
Even though I use it for Doctest, I get this warning. I see we didn't use a non-prelude library for our doctests before, but I want to handle a case with `Map` since @igrep noticed the bug with that data structure.
We can overcome this warning with `{-# OPTIONS_GHC -fno-warn-unused-imports #-}` pragma on this module. What do you think?
=> Fix trace functions not pretty-printing as expected

app/Main.hs, pretty-simple.cabal
#34 . Not super comfortable with this, but I guess it works. Allows optional argument --color or -c with options dark-bg, light-bg, no-color (default dark-bg).
=> Allow light-bg and no-color modes for executable

CHANGELOG.md, pretty-simple.cabal, src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/ExprParser.hs, src/Text/Pretty/Simple/Internal/ExprToOutput.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs
=> Lazy parser

src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/ExprParser.hs, src/Text/Pretty/Simple/Internal/ExprToOutput.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs
This just adds an additional test that shows that `pretty-simple` correctly prints out unicode.
(#37 should be merged in before this.)
=> Additional unicode test

src/Text/Pretty/Simple/Internal/ExprParser.hs
I simply added a case for ignoring the next character after a backslash in `parseStringLit`.
Fixes #40.
=> Quick fix for issue #40

CHANGELOG.md, pretty-simple.cabal, src/Debug/Pretty/Simple.hs, src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs, stack.yaml
Closes #46.
Seems to work but please recheck.
=> Add TTY detection

.travis.yml, CHANGELOG.md, Setup.hs, pretty-simple.cabal, src/Text/Pretty/Simple/Internal/Color.hs, src/Text/Pretty/Simple/Internal/Expr.hs, src/Text/Pretty/Simple/Internal/ExprParser.hs, src/Text/Pretty/Simple/Internal/ExprToOutput.hs, src/Text/Pretty/Simple/Internal/Output.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs, test/DocTest.hs
This adds highlighting to numbers, closes #4.  Also closes #49.
It's a pretty straightforward diff on the whole. We add a `NumberLit` constructor to `Expr`, and a `OutputNumberLit` to `OutputType`. These are hooked up in the obvious way.
Then we have a function `parseNumberLit` for parsing numbers. I've just handled integers (strings matching the regex `[0-9]+`) and decimals (strings matching the regex `[0-9]+\.[0-9]+`) for now. There is a question here about what exactly we want to treat as a number. You could imagine that maybe we would want to extend this in future to cover some or all of
- hex/octal/binary syntax,
- exponents in decimal notation (like `1e2` for example),
- numeric underscores,
- omitted leading digits (like `.123`),
- leading plus/minus signs?
A more tricky change is …
=> Highlight numbers

CHANGELOG.md, pretty-simple.cabal, src/Text/Pretty/Simple.hs
This patch implements pPrintString, pPrintStringOpt and pHPrintStringOpt
functions that are similar to their pPrint counterparts except they take
the 'show'ed string of the data type. Fixes #53
=> Add pPrintString function

CHANGELOG.md, pretty-simple.cabal, src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/Expr.hs, src/Text/Pretty/Simple/Internal/ExprParser.hs, src/Text/Pretty/Simple/Internal/ExprToOutput.hs, src/Text/Pretty/Simple/Internal/Output.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs
=> Fix handling of Char literals

src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs
=> Remove trailing whitespaces from the end of lines

src/Text/Pretty/Simple/Internal/ExprParser.hs
Closes #63.
This works by simply using the same logic for `'` that we use for digits w.r.t. appearing in identifiers. Obviously they're not entirely equivalent in general because `'` can only appear at the end of an identifier, but I don't believe there's any situation here where that difference is important.
=> Fix parsing for identifiers containing "'"

src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/Color.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs
Using `prettyprinter-ansi-terminal`'s `AnsiStyle` to represent colours was not ideal as it is intentionally opaque, and so it's difficult to convert to another format.
This PR introduces a new `Style` type corresponding to the subset of `AnsiStyle` which is used in `pretty-simple`.
There is some inconsistency in whether we refer to things as "style"s or "colour"s. This `Style` type allows customising whether the text is bold, so it does represent more than just colour. But changing all instances of "color" to "style" would seem an unnecessary break of backwards compatibility. This isn't really a new issue, but this change has made it more obvious.
=> Changes to enable usage of prettyprinter backends

src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/OutputPrinter.hs
=> Add option for initial indentation

app/Main.hs, pretty-simple.cabal
This flag prints out the version of pretty-simple:
```console
$ pretty-simple --version
4.0.0.0
```
I've wanted this for a while, and it would have helped me avoid posting https://github.com/cdepillabout/pretty-simple/issues/79.
=> Add --version flag to pretty-simple CLI

pretty-simple.cabal
=> Default to always building executable

README.md
Closes #92.
I'm fairly sure `-b` is a safer option than `--package`. In fact, I'm not quite sure what `--package` even does - I think it's a legacy `v1-` thing. `-b` will consult the solver, build a version of `pretty-simple` compatible with the current environment, add it to the global cache, and bring it in to scope in GHCI.
=> Add `cabal repl` instructions to README

src/Debug/Pretty/Simple.hs
#101 
Straightforward. Implemented like protolude has implemented, but could use the DEPRECATED pragma instead. Let's discuss.
=> Added warnings for deprecation

src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/Printer.hs
=> Fewer spaces

README.md
The images in README are not displayed on [Hackage](https://hackage.haskell.org/package/pretty-simple) because the paths are relative. So I've changed URLs to absolute ones. I think some people still encounter `pretty-simple` on Hackage as their first occurrence so it would be good to have images displayed there as well 🎨 
I also pessimistically removed the _title_ part of the markdown rendering not being sure whether the current Hackage markdown supports this. To test this, one needs to create candidate releases and check the output 🤔 
P.S. Feel free to close this PR if this is not what you want 🙂
=> Use absolute URLs for images in README.md

src/Text/Pretty/Simple.hs, src/Text/Pretty/Simple/Internal/Printer.hs, stack.yaml
This seems to rather make the compact output have less newline commas: addressing #84.
eg 
```
( "request"
, ValueArray
[ ValueString "git+https://src.fedoraproject.org/rpms/rpmbuild-order.git#6a9f3fce18040a2020d37707abb82445e1884e69"
, ValueString "f37-build-side-54239"
, ValueStruct
[
( "fail_fast", ValueBool True )
,
( "wait_builds", ValueArray [] )
,
( "custom_user_metadata", ValueStruct [] ) ] ] )
,
( "result"
, ValueStruct
[
( "faultCode", ValueInt 1000 )
,
( "faultString"
, ValueString "bad filename: A-1-1.fc37.buildreqs.nosrc.rpm (expected A-1-1.fc37.src.rpm)" ) ] )
,
( "start_time", ValueString "2022-05-31 02:27:37.208059+00:00" )
```
becomes
```
( "request", ValueArray
[ ValueString "git+https://src.fedoraproject.org/rpms/rpmbuild-order.git#6a9f3fce18040a2020d37707abb82445e1884e6 …
```
=> further reduce newlines for compact output

src/Text/Pretty/Simple.hs
Closes https://github.com/cdepillabout/pretty-simple/issues/114.
=> Use correct handle for newline output

.github/workflows/ci.yml
This PR just modifies CI to only build `web` with Nix, and have the cabal CI jobs only build the `pretty-simple` package, not `web`.
It also updates the GHC versions used in CI.
This PR should hopefull be able to be directly merged into https://github.com/cdepillabout/pretty-simple/pull/116.
=> Only build pretty-simple package in cabal CI. Build web with Nix in CI.

web/README.md, web/src/Main.hs
This PR is for #116.  It just adds a simple explanation of how to run a local web server.
=> Add explanation how to run local web server

cabal.project
Undoes https://github.com/cdepillabout/pretty-simple/pull/125.
=> Remove no-longer-needed JSaddle workarounds

.gitignore
This file, obtained by running `cabal configure`, is designed not to be checked in.
=> Add `cabal.project.local` to `.gitignore`
